# -*- coding: utf-8 -*-
"""webapp.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11wdLojwRECyMwfp7JjrESYmWBK1fsSGH
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

# Try to read existing data or create a new empty dataframe
try:
    dados = pd.read_csv("compras.csv")
except:
    dados = pd.DataFrame({"produto": [], "preco": []})
    dados.to_csv("compras.csv", index=False)

# Streamlit interface
st.title("Controle de Gastos")

# Budget input
orcamento = st.number_input("Orçamento:", min_value=0.0)

# Calculate total spending
total = dados["preco"].sum() if not dados.empty else 0

# Form for adding a new purchase
with st.form("nova_compra"):
    produto = st.text_input("Produto:")
    preco = st.number_input("Preço:", min_value=0.0)

    # Submit button for the form
    if st.form_submit_button("Adicionar"):
        if preco <= (orcamento - total):
            nova_linha = pd.DataFrame({"produto": [produto], "preco": [preco]})
            dados = pd.concat([dados, nova_linha])
            dados.to_csv("compras.csv", index=False)
            st.success("Compra adicionada!")
        else:
            st.error("Sem orçamento suficiente!")

# Display budget and total
if orcamento > 0:
    # Create a donut chart if there is budget and data
    fig, ax = plt.subplots(figsize=(8, 8))
    if not dados.empty:
        produtos = dados["produto"].tolist()
        valores = dados["preco"].tolist()
        restante = orcamento - total
        if restante > 0:
            produtos.append("Disponível")
            valores.append(restante)
        ax.pie(valores, labels=produtos, autopct='%1.1f%%', pctdistance=0.85)
        plt.title(f"Orçamento: {orcamento}€")

    # Add the center white circle to create the donut chart effect
    centro = plt.Circle((0, 0), 0.70, fc='white')
    ax.add_artist(centro)

    # Display the chart and data
    st.pyplot(fig)
    st.dataframe(dados)
    st.write(f"Total gasto: {total}€")
    st.write(f"Restante: {orcamento - total}€")